# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Ari Ramkilowan
tagline:             A written account of my journey via data science
#description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://iamari.github.io/blog/
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Ari Ramkilowan
  url:               https://twitter.com/Legend_Ari
  email:             ari.ramkilowan@gmail.com

# Custom vars
version:             1.0.0
